from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='''<section class="reviews-section" aria-labelledby="reviews-title"><div class="container reviews-layout"><div class="reviews-intro"><p class="eyebrow">СЛОВА, КОТОРЫЕ СОГРЕВАЮТ</p><h2 id="reviews-title">Ваши<br> <em>впечатления.</em></h2><a class="review-rating" href="https://dikidi.net/1006138" target="_blank" rel="noopener noreferrer"><strong>4,7<span>/ 5</span></strong><span>26 оценок в DIKIDI <svg class="icon"><use href="#i-up"/></svg></span></a></div><div class="review-cards"><figure class="review-card"><div class="review-top"><span class="quote-mark" aria-hidden="true">“</span><span class="review-source">DIKIDI</span></div><blockquote>Результат радует: ногти красивые, ровные, покрытие держится долго.</blockquote><figcaption><span class="review-initial" aria-hidden="true">О</span><span><strong>Ольга</strong><span>6 мая 2026 · мастер Яна</span></span></figcaption></figure><figure class="review-card"><div class="review-top"><span class="quote-mark" aria-hidden="true">“</span><span class="review-source">DIKIDI</span></div><blockquote>Спасибо за красоту, антистресс-терапию в процессе и быструю, а главное, качественную работу.</blockquote><figcaption><span class="review-initial" aria-hidden="true">А</span><span><strong>Анастасия</strong><span>21 марта 2026 · мастер Эмилия</span></span></figcaption></figure><a class="text-link all-reviews" href="https://dikidi.net/1006138" target="_blank" rel="noopener noreferrer">Читать все отзывы в DIKIDI <svg class="icon"><use href="#i-up"/></svg></a></div></div></section>'''
new='''<section class="reviews-section" aria-labelledby="reviews-title"><div class="container reviews-layout"><div class="reviews-intro"><p class="eyebrow">СЛОВА, КОТОРЫЕ СОГРЕВАЮТ</p><h2 id="reviews-title">Ваши<br> <em>впечатления.</em></h2><a class="review-rating" href="https://yandex.ru/maps/org/amur/202060827340/reviews/" target="_blank" rel="noopener noreferrer"><strong>5,0<span>/ 5</span></strong><span>62 оценки на Яндекс Картах <svg class="icon"><use href="#i-up"/></svg></span></a></div><div class="review-cards"><figure class="review-card"><div class="review-top"><span class="quote-mark" aria-hidden="true">“</span><span class="review-source">ЯНДЕКС КАРТЫ</span></div><blockquote>Здесь царит приятная атмосфера: чисто, удобно, персонал внимателен к пожеланиям.</blockquote><figcaption><span class="review-initial" aria-hidden="true">О</span><span><strong>Ольга Медведкова</strong><span>6 мая · Яндекс Карты</span></span></figcaption></figure><figure class="review-card"><div class="review-top"><span class="quote-mark" aria-hidden="true">“</span><span class="review-source">ЯНДЕКС КАРТЫ</span></div><blockquote>Мастер очень приятный, вежливо относится к клиенту, приятная обстановка. Сделала всё аккуратно и красиво.</blockquote><figcaption><span class="review-initial" aria-hidden="true">И</span><span><strong>Ирина Мосылёва</strong><span>14 января · Яндекс Карты</span></span></figcaption></figure><a class="text-link all-reviews" href="https://yandex.ru/maps/org/amur/202060827340/reviews/" target="_blank" rel="noopener noreferrer">Читать все отзывы на Яндекс Картах <svg class="icon"><use href="#i-up"/></svg></a></div></div></section>'''
if old not in s: raise SystemExit('reviews block not found')
s=s.replace(old,new)
s=s.replace('Мастера, отзывы, режим работы и дополнительные услуги сверены с открытой карточкой <a href="https://dikidi.net/1006138" target="_blank" rel="noopener noreferrer">DIKIDI</a> 9 сентября 2026 года.', 'Мастера, режим работы и дополнительные услуги сверены с открытой карточкой <a href="https://dikidi.net/1006138" target="_blank" rel="noopener noreferrer">DIKIDI</a>, а рейтинг и отзывы — с <a href="https://yandex.ru/maps/org/amur/202060827340/reviews/" target="_blank" rel="noopener noreferrer">Яндекс Картами</a> 9 сентября 2026 года.')
p.write_text(s,encoding='utf-8')
print('Yandex reviews installed')
